### ISSUE TITLE
Pes 21 Support on soFIFA?

### ISSUE THREAD

**Issue by ArdaKurucim** [moth1995/pes_stats_converter_copy_addon#2]
Can you somehow add it?

**Comment by moth1995** [comment]
Hi! As I already explained before, its possible although I'm not an expert on stats, neither on PES21, someone must provide the formulas to convert stats from sofifa into PES21 and if I get some free time I will port it into the code, otherwise if someone else could help with the code its very welcome!

**Comment by ArdaKurucim** [comment]
I also have no idea hahaha. I just wanted to update player stats to the newest one since eFootball 25 sucks. Maybe I have to wait for someone's help. Thank you!
